// frontend/src/components/Navbar.tsx
import React, { useState } from 'react';
import { ShoppingCart, CheckCircle } from 'lucide-react';
import { useCart } from '../context/CartContext';

export default function Navbar() {
  const { totalItems, toggleCart } = useCart();
  const [showToast, setShowToast] = useState(false);

  const handleBookTable = () => {
    setShowToast(true);
    setTimeout(() => setShowToast(false), 3000);
  };

  const scrollToTop = (e: React.MouseEvent) => {
    e.preventDefault();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const scrollToMenu = (e: React.MouseEvent) => {
    e.preventDefault();
    document.getElementById('menu')?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <>
      <nav className="fixed top-4 left-1/2 -translate-x-1/2 w-[95%] max-w-6xl z-50 bg-[#0a0a0c]/80 backdrop-blur-xl border border-gray-800/60 shadow-[0_8px_32px_rgba(0,0,0,0.5)] rounded-2xl px-8 py-4 flex justify-between items-center transition-all duration-300 hover:border-[#d4af37]/30">
        <div className="flex items-center gap-4 cursor-pointer group" onClick={scrollToTop}>
          <img src="/logo.png" alt="Best Khmer Restaurant Logo" className="h-12 w-auto rounded-full group-hover:scale-105 transition-transform duration-500 shadow-[0_0_15px_rgba(212,175,55,0.2)]" />
          <div className="font-['Playfair_Display'] text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-white to-[#d4af37] tracking-wider group-hover:to-[#f3e5ab] transition-all">
            Best Khmer
          </div>
        </div>
        
        <ul className="hidden md:flex gap-10 font-medium">
          <li><a href="#" onClick={scrollToTop} className="hover:text-[#d4af37] transition-colors relative group text-gray-300">Home<span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-[#d4af37] transition-all group-hover:w-full"></span></a></li>
          <li><a href="#menu" onClick={scrollToMenu} className="hover:text-[#d4af37] transition-colors relative group text-gray-300">Menu<span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-[#d4af37] transition-all group-hover:w-full"></span></a></li>
        </ul>

        <div className="flex items-center gap-6">
          <button 
            onClick={toggleCart} 
            className="relative text-gray-300 hover:text-[#d4af37] hover:scale-110 transition-all duration-300"
            title="View Cart"
          >
            <ShoppingCart size={24} />
            {totalItems > 0 && (
              <span className="absolute -top-2 -right-2 bg-gradient-to-r from-[#d4af37] to-[#f3e5ab] text-black text-xs font-bold w-5 h-5 flex items-center justify-center rounded-full shadow-[0_0_15px_rgba(212,175,55,0.6)] animate-bounce">
                {totalItems}
              </span>
            )}
          </button>
          <button onClick={handleBookTable} className="btn-primary hidden sm:block shadow-[0_4px_20px_rgba(212,175,55,0.2)] hover:shadow-[0_4px_25px_rgba(212,175,55,0.4)] transform hover:-translate-y-0.5 transition-all">
            Book a Table
          </button>
        </div>
      </nav>

      {/* Toast Notification */}
      <div className={`fixed bottom-8 left-1/2 -translate-x-1/2 z-50 transition-all duration-500 transform ${showToast ? 'translate-y-0 opacity-100' : 'translate-y-20 opacity-0 pointer-events-none'}`}>
        <div className="bg-gray-900/90 backdrop-blur-md border border-[#d4af37]/50 shadow-[0_10px_40px_rgba(0,0,0,0.8)] text-white px-6 py-4 rounded-xl flex items-center gap-3">
          <CheckCircle className="text-[#d4af37]" size={24} />
          <div>
            <h4 className="font-bold text-[#d4af37] font-['Playfair_Display'] text-lg">Table Reservations</h4>
            <p className="text-gray-300 text-sm">Online reservations coming soon!</p>
          </div>
        </div>
      </div>
    </>
  );
}

// legacy-vue-frontend/src/components/Navbar.vue
<script setup>
import { store } from '../store.js'
import { computed } from 'vue'

const cartItemCount = computed(() => {
  return store.cart.reduce((total, item) => total + item.quantity, 0)
})
</script>

<template>
  <nav class="navbar glass-panel">
    <div class="container nav-content">
      <div class="brand">
        <img src="/logo.png" alt="Best Khmer Restaurant Logo" class="brand-logo" />
        <div class="logo">Best Khmer Restaurant</div>
      </div>
      <ul class="nav-links">
        <li><a href="#home">Home</a></li>
        <li><a href="#menu">Menu</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
      <div class="nav-actions">
        <button class="cart-btn" @click="store.isCartOpen = true">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="9" cy="21" r="1"></circle>
            <circle cx="20" cy="21" r="1"></circle>
            <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path>
          </svg>
          <span v-if="cartItemCount > 0" class="cart-badge">{{ cartItemCount }}</span>
        </button>
        <button class="btn-primary" @click="store.isBookingModalOpen = true">Book a Table</button>
      </div>
    </div>
  </nav>
</template>

<style scoped>
.navbar {
  position: fixed;
  top: 1rem;
  left: 50%;
  transform: translateX(-50%);
  width: 90%;
  max-width: 1200px;
  z-index: 1000;
  border-radius: 50px;
}

.nav-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem 2rem;
}

.brand {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.brand-logo {
  height: 40px;
  width: auto;
  border-radius: 50%;
}

.logo {
  font-family: 'Playfair Display', serif;
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--color-primary);
  letter-spacing: 1px;
}

.nav-links {
  display: flex;
  list-style: none;
  gap: 2.5rem;
}

.nav-links a {
  font-size: 0.95rem;
  font-weight: 400;
  color: var(--color-text);
  position: relative;
}

.nav-links a::after {
  content: '';
  position: absolute;
  bottom: -4px;
  left: 0;
  width: 0;
  height: 2px;
  background-color: var(--color-primary);
  transition: var(--transition-smooth);
}

.nav-links a:hover {
  color: var(--color-primary);
}

.nav-links a:hover::after {
  width: 100%;
}

.nav-actions {
  display: flex;
  align-items: center;
  gap: 1.5rem;
}

.cart-btn {
  background: transparent;
  border: none;
  color: var(--color-text);
  cursor: pointer;
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: var(--transition-smooth);
}

.cart-btn:hover {
  color: var(--color-primary);
  transform: scale(1.1);
}

.cart-badge {
  position: absolute;
  top: -8px;
  right: -10px;
  background: var(--color-primary);
  color: var(--color-bg);
  font-size: 0.75rem;
  font-weight: 700;
  width: 20px;
  height: 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  box-shadow: 0 0 10px var(--color-primary-glow);
}
</style>
